### ISSUE TITLE
Checklist (Qualidade dos vídeos)

### ISSUE THREAD

**Issue by allluz** [w3b3d3v/content-videos-PT#52]
## Proposta (grant, video-votação, core strategy)
- [ ] seleção e aprovação da ideia no Discord;
- [ ] encaixe de grant para conteúdo nas playlists semanais;
- [ ] distribuição mensal de conteúdo por meio de playlists de acordo com os temas dos grupos de estudos ou palavras-chave para SEO;

### Modelo de playlists 
- [ ] título da playlist respondendo a uma dúvida (SEO)
- [ ] tema macro igual aos dos grupos de estudos;
- [ ] 4 vídeos (mínimo) por playlist para publicação semanal;
- [ ] variar direcionamento para cada um dos vídeos da playlist (vídeo técnico, em lista, explicação de conceitos, trend atual do mercado);

## Gravação
Exemplo: https://drive.google.com/drive/folders/1yl_Y8YzwwokdK49xaw1hLazsR4i9r1Ew?hl=pt-br
- [ ] cenário (chroma key intro e fundo transparent Durante exibição de câmera)
- [ ] áudio e imagem ok
- [ ] linguagem técnica e formal (usar termos da marca como builder, construção, builds, codar etc);
- [ ] intro video apresentando tema, playlist e sumário.
- [ ] intro video convidando para se conectar ao discord, se inscrever e ativar as notificações do canal.
- [ ] modelos de apresentação com branding da marca;
- [ ] cta pra grupos de estudos do respectivo tema e convite pra acompanhar o próximo vídeo da playlist sobre o tema;

## Edição
- [ ] vinheta inicial entre intro e conteúdo;
- [ ] usar títulos minimalistas;
- [ ] tags, sumário, link do discord e dos grupos de estudo na descrição;
- [ ] configurar hashtags, idioma, restrições de idade etc nas configurações de publicação;
- [ ] thumb customizada de acordo com tema do vídeo (usar template porém customizado);
- [ ] pops ups com brand da marca durante o vídeo com convites para se conectar ao discord ou se inscrever no canal, além das nossas redes sociais;
- [ ] qr code com link dos grupos durante os vídeos;
- [ ] vinheta final;

**Comment by allluz** [comment]
# Template para criação de Vídeos

Com o objetivo de padronizar os vídeos criados no canal da comunidade, usaremos um roteiro básico para estruturar os vídeos.
Segue o exemplo a ser seguido:

## mini-chamada-10s

''Quer aprender <título do vídeo>
Então assiste esse vídeo até o final…''

</ final da mini-chamada-10s>

<vinheta> [Aqui o editor vai inserir a vinheta da web3dev] </vinheta>

## Introdução
Olá builder, eu sou <seu-nome> Daniel Cukier, também conhecido como danicuki.</seu-username>
Aqui nós somos a web3dev, um canal com conteúdo exclusivo sobre web3 para developers. Se você quer ser parte da construção da nova Internet, considere se inscrever aqui no canal e também acessar o Discord no endereço discord.web3dev.com.br
</ final da introdução>

## Tema do vídeo
O assunto de hoje é <assunto-da-vez> NEAR Protocol. </assunto-da-vez>
<explicação-rápida> Vou mostrar aqui pra vocês como fazer
uma transação na NEAR usando apenas JavaScript. </explicação-rápida>
</tema-do-video>
<conteúdo>
...
</conteúdo>

Assistiu até o final? Comente #falabuilder ou alguma frase/palavra relacionada ao conteúdo.

## Chamada para Grupos de Estudos
<final>

Se você gostou desse conteúdo, deixa aqui o seu like e compartilha com a sua comunidade. Vamos construir a nova internet juntos!
WEB3DEV, we're all gonna build it! WAGBI

</final>

**Comment by allluz** [comment]
# Suporte para edição

## Thumbnail para vídeos técnicos

![Image](https://github.com/w3b3d3v/squad-midiatico-videos-PT/assets/122928421/d3fad340-9089-4de2-ac3a-224f698071b1)

https://www.canva.com/design/DAF-rHdkgQw/9PShlT-rRGQQDppKom3lKA/view?utm_content=DAF-rHdkgQw&utm_campaign=designshare&utm_medium=link&utm_source=sharebutton&mode=preview

## Chamada de Ação para Grupo de Estudos

![Image](https://github.com/w3b3d3v/squad-midiatico-videos-PT/assets/122928421/2411ea91-bc7c-459a-a2ca-b88f6ee8e310)

## End Video





https://www.canva.com/design/DAGDW72RcdQ/Qb0iOiv-2BRZycze-GA5_Q/edit?utm_content=DAGDW72RcdQ&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton



# CTA para a descrição dos vídeos técnicos

## CTA Geral

🌟 Quer aprofundar seu conhecimento em tecnologias disruptivas como blockchain, smart contracts ou programação em Rust ou Solidity? 👉 Acesse o Nosso Discord Agora: https://l.w3d.community/discord 

Não perca mais tempo! 🚀 Junte-se agora mesmo ao nosso grupo de estudos e faça parte de uma comunidade que está na vanguarda da inovação tecnológica. Conecte-se, aprenda e cresça com especialistas e entusiastas.

**Comment by allluz** [comment]
# CTA para a descrição dos grupos de estudos

## Rust

💻 Quer dominar uma das linguagens de programação mais seguras e eficientes do mercado?
🔗 Junte-se ao nosso grupo de estudos de Rust! https://l.w3d.community/grupos

📚 Um lugar onde você aprenderá a desenvolver aplicações Web e blockchain. Ideal para programadores que buscam elevar sua eficiência e segurança no código, explorando as características únicas que Rust oferece.

🌐 Participe da WEB3DEV no Discord: Não perca a oportunidade de fazer parte da revolução tecnológica! Compartilhe suas opiniões, aprenda e ajude a construir o futuro da tecnologia blockchain.

👉 Acesse nosso Discord agora: https://l.w3d.community/discord

#rust #guia #blockchain #web3 #polygon #desenvolvedores #RustStateMachine



![Image](https://github.com/w3b3d3v/squad-midiatico-videos-PT/assets/122928421/ecb55d2c-ec60-445f-8017-8fe140aba245)



## Solidity

💻 Quer dominar a linguagem de programação usada para criar contratos inteligentes na Ethereum?
🔗 Junte-se ao nosso grupo de estudos de Solidity! https://l.w3d.community/grupos

📚 Um lugar onde você aprenderá a desenvolver contratos inteligentes seguros e eficientes. Ideal para programadores que buscam aprimorar suas habilidades em blockchain, explorando as características únicas que Solidity oferece.

🌐 Participe da WEB3DEV no Discord: Não perca a oportunidade de fazer parte da revolução tecnológica! Compartilhe suas opiniões, aprenda e ajude a construir o futuro da tecnologia blockchain.

👉 Acesse nosso Discord agora: https://l.w3d.community/discord

#solidity #guia #blockchain #web3 #ethereum #desenvolvedores #SmartContracts



![Image](https://github.com/w3b3d3v/squad-midiatico-videos-PT/assets/122928421/5745a38d-82d0-47fc-91cb-b50c837ce454)



## Segurança de Smart Contracts

🛡️ Quer aprender a proteger contratos inteligentes contra vulnerabilidades e ataques?
🔗 Junte-se ao nosso grupo de estudos de Segurança de Smart Contracts! https://l.w3d.community/grupos

📚 Um lugar onde você aprenderá técnicas avançadas para auditar e garantir a segurança de contratos inteligentes. Ideal para desenvolvedores que desejam aprofundar seus conhecimentos em práticas de segurança críticas, explorando métodos e ferramentas essenciais para proteger aplicações blockchain.

🌐 Participe da WEB3DEV no Discord: Engaje-se em discussões enriquecedoras, compartilhe experiências e aprenda com especialistas em segurança de blockchain.

👉 Acesse nosso Discord agora: https://l.w3d.community/discord

#smartcontractsecurity #guia #blockchain #web3 #cybersecurity #desenvolvedores #BlockchainSecurity
